// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pssgmxqlvxkfvejpctxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzc2dteHFsdnhrZnZlanBjdHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODMwODgsImV4cCI6MjA2MTU1OTA4OH0.cU4sjnm72rJ2ib_ML7xf6tOfS4blmBwnlBbXIgCPGd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);